CREATE TABLE [Users] (
    [UserID] INT PRIMARY KEY IDENTITY(1, 1),
    [UserGuid] VARCHAR(36) DEFAULT (CONVERT(VARCHAR(256), NEWID())) NOT NULL,
    [CreatedAt] DATETIME2 DEFAULT (GETUTCDATE()) NOT NULL,
    [LastLoginAt] DATETIME2,
    [IsActive] BIT DEFAULT (1) NOT NULL
)